param(
    [string]$Version = "1.3.4"
)

$ErrorActionPreference = "Stop"

$modId = "mr_diamond_recycling"
$buildDir = "build"
$outputJar = Join-Path $buildDir "diamond-recycling-$Version.jar"
$tempDir = "temp_build"

function Copy-PackDirectory {
    param(
        [string]$Source,
        [string]$DestinationRoot
    )

    if (-not (Test-Path $Source)) {
        throw "Required directory '$Source' was not found."
    }

    Copy-Item -Path $Source -Destination $DestinationRoot -Recurse -Force
}

function Assert-ZipContainsPrefix {
    param(
        [string]$ArchivePath,
        [string]$Prefix
    )

    Add-Type -AssemblyName System.IO.Compression.FileSystem
    $archive = [System.IO.Compression.ZipFile]::OpenRead((Resolve-Path $ArchivePath))

    try {
        $hasMatch = $archive.Entries | Where-Object { $_.FullName.StartsWith($Prefix) } | Select-Object -First 1
        if (-not $hasMatch) {
            throw "Archive '$ArchivePath' is missing expected content under '$Prefix'."
        }
    }
    finally {
        $archive.Dispose()
    }
}

Write-Host "Building Diamond Recycling v$Version..." -ForegroundColor Cyan

if (Test-Path $tempDir) {
    Remove-Item $tempDir -Recurse -Force
}

if (-not (Test-Path $buildDir)) {
    New-Item -ItemType Directory -Path $buildDir | Out-Null
}

if (Test-Path $outputJar) {
    Remove-Item $outputJar -Force
}

New-Item -ItemType Directory -Path $tempDir | Out-Null
New-Item -ItemType Directory -Path "$tempDir/META-INF" | Out-Null

Write-Host "Copying data pack files..." -ForegroundColor Yellow

Copy-Item "pack.mcmeta" "$tempDir/pack.mcmeta"
Copy-Item "pack.png" "$tempDir/diamond-recycling_pack.png"
Copy-Item "credits.txt" "$tempDir/credits.txt"
Copy-Item "license.txt" "$tempDir/license.txt"

Copy-PackDirectory -Source "data" -DestinationRoot $tempDir
Copy-PackDirectory -Source "overlay_57" -DestinationRoot $tempDir
Copy-PackDirectory -Source "overlay_71" -DestinationRoot $tempDir

Write-Host "Creating mod metadata files..." -ForegroundColor Yellow

$fabricMod = @{
    schemaVersion = 1
    id = $modId
    version = $Version
    name = "Diamond Recycling"
    description = "Recycle diamond tools, diamond armor, and smithing templates into diamonds through crafting."
    authors = @("notblue")
    contact = @{
        homepage = "https://modrinth.com/datapack/diamond-recycling"
        sources = "https://github.com/not-blue/diamond-recycling"
        issues = "https://github.com/not-blue/diamond-recycling/issues"
    }
    license = "CC-BY-NC-SA-4.0"
    icon = "diamond-recycling_pack.png"
    environment = "*"
    depends = @{
        "fabric-resource-loader-v0" = "*"
    }
}
$fabricMod | ConvertTo-Json -Compress | Set-Content "$tempDir/fabric.mod.json" -Encoding UTF8

$quiltMod = @{
    schema_version = 1
    quilt_loader = @{
        group = "com.modrinth"
        id = $modId
        version = $Version
        metadata = @{
            name = "Diamond Recycling"
            description = "Recycle diamond tools, diamond armor, and smithing templates into diamonds through crafting."
            contributors = @{
                notblue = "Member"
            }
            contact = @{
                homepage = "https://modrinth.com/datapack/diamond-recycling"
                sources = "https://github.com/not-blue/diamond-recycling"
                issues = "https://github.com/not-blue/diamond-recycling/issues"
            }
            icon = "diamond-recycling_pack.png"
        }
        intermediate_mappings = "net.fabricmc:intermediary"
        depends = @(
            @{
                id = "quilt_resource_loader"
                versions = "*"
                unless = "fabric-resource-loader-v0"
            }
        )
    }
}
$quiltMod | ConvertTo-Json -Depth 10 -Compress | Set-Content "$tempDir/quilt.mod.json" -Encoding UTF8

$forgeMods = @"

modLoader = 'lowcodefml'
loaderVersion = '[40,)'
license = 'CC-BY-NC-SA-4.0'
showAsResourcePack = false
mods = [
	{ modId = '$modId', version = '$Version', displayName = 'Diamond Recycling', description = 'Recycle diamond tools, diamond armor, and smithing templates into diamonds through crafting.', logoFile = 'diamond-recycling_pack.png', updateJSONURL = 'https://api.modrinth.com/updates/jw67t8zN/forge_updates.json', credits = 'Generated by Modrinth', authors = 'notblue', displayURL = 'https://modrinth.com/datapack/diamond-recycling' },
]
issueTrackerURL = 'https://github.com/not-blue/diamond-recycling/issues'
"@
$forgeMods | Set-Content "$tempDir/META-INF/mods.toml" -Encoding UTF8

$neoForgeMods = @"

modLoader = 'javafml'
loaderVersion = '[1,)'
license = 'CC-BY-NC-SA-4.0'
showAsResourcePack = false
mods = [
	{ modId = '$modId', version = '$Version', displayName = 'Diamond Recycling', description = 'Recycle diamond tools, diamond armor, and smithing templates into diamonds through crafting.', logoFile = 'diamond-recycling_pack.png', updateJSONURL = 'https://api.modrinth.com/updates/jw67t8zN/forge_updates.json?neoforge=only', credits = 'Generated by Modrinth', authors = 'notblue', displayURL = 'https://modrinth.com/datapack/diamond-recycling' },
]
issueTrackerURL = 'https://github.com/not-blue/diamond-recycling/issues'
"@
$neoForgeMods | Set-Content "$tempDir/META-INF/neoforge.mods.toml" -Encoding UTF8

Write-Host "Creating JAR file..." -ForegroundColor Yellow

$compress = @{
    Path = (Join-Path $tempDir "*")
    CompressionLevel = "Optimal"
    DestinationPath = $outputJar
}
Compress-Archive @compress

Assert-ZipContainsPrefix -ArchivePath $outputJar -Prefix "data/"
Assert-ZipContainsPrefix -ArchivePath $outputJar -Prefix "overlay_57/"
Assert-ZipContainsPrefix -ArchivePath $outputJar -Prefix "overlay_71/"

Remove-Item $tempDir -Recurse -Force

Write-Host "Build complete: $outputJar" -ForegroundColor Green
Write-Host "File size: $([math]::Round((Get-Item $outputJar).Length / 1KB, 2)) KB" -ForegroundColor Green
